-- =====================================================================
--  Marlen Sweets — update 04 (speed)
--  Saving a product (details + occasions + photo order) in ONE request instead of 6–8,
--  and the dashboard numbers in one request. Important on slow connections.
--  Paste into Supabase → SQL Editor → New query → Run. Safe to run more than once.
-- =====================================================================

-- p:       product fields as JSON (id is generated by the admin for new products)
-- occ:     selected occasion ids
-- images:  final ordered list of photos: [{ "id": <existing id or null>, "path": "products/…" }, …]
-- returns: { id, slug, images: [...saved rows...], removed: [paths of deleted photos] }
create or replace function public.admin_save_product(p jsonb, occ uuid[], images jsonb, is_new boolean)
returns jsonb
language plpgsql
security invoker            -- runs with the caller's rights, so RLS still applies
set search_path = ''
as $$
declare
  pid uuid := (p->>'id')::uuid;
  cat uuid := (p->>'category_id')::uuid;
  base_slug text := coalesce(nullif(p->>'slug', ''), 'item');
  new_slug text := base_slug;
  removed text[];
begin
  if not public.is_admin() then
    raise exception 'permission denied' using errcode = '42501';
  end if;

  if is_new then
    while exists (select 1 from public.products where slug = new_slug) loop
      new_slug := base_slug || '-' || substr(md5(random()::text), 1, 4);
    end loop;
    insert into public.products (id, category_id, slug, name_ar, name_en, description_ar, description_en, is_visible, is_featured, sort_order)
    values (pid, cat, new_slug, p->>'name_ar', coalesce(p->>'name_en', ''),
            coalesce(p->>'description_ar', ''), coalesce(p->>'description_en', ''),
            coalesce((p->>'is_visible')::boolean, true), coalesce((p->>'is_featured')::boolean, false),
            coalesce((select min(sort_order) from public.products where category_id = cat), 1) - 1);
  else
    update public.products set
      category_id = cat,
      name_ar = p->>'name_ar',
      name_en = coalesce(p->>'name_en', ''),
      description_ar = coalesce(p->>'description_ar', ''),
      description_en = coalesce(p->>'description_en', ''),
      is_visible = coalesce((p->>'is_visible')::boolean, true),
      is_featured = coalesce((p->>'is_featured')::boolean, false)
    where id = pid;
    if not found then raise exception 'product not found'; end if;
  end if;

  -- occasions
  delete from public.product_occasions where product_id = pid and not (occasion_id = any (coalesce(occ, '{}')));
  insert into public.product_occasions (product_id, occasion_id)
  select pid, o from unnest(coalesce(occ, '{}')) as o
  on conflict do nothing;

  -- photos: delete the ones no longer in the list, add new ones, save the order
  with gone as (
    delete from public.product_images
    where product_id = pid
      and id not in (select (e->>'id')::uuid from jsonb_array_elements(images) e where e->>'id' is not null)
    returning path
  )
  select array_agg(path) into removed from gone;

  update public.product_images pi set sort_order = e.ord - 1
  from jsonb_array_elements(images) with ordinality as e(val, ord)
  where pi.product_id = pid and e.val->>'id' is not null and pi.id = (e.val->>'id')::uuid;

  insert into public.product_images (product_id, path, sort_order)
  select pid, e.val->>'path', e.ord - 1
  from jsonb_array_elements(images) with ordinality as e(val, ord)
  where e.val->>'id' is null;

  return jsonb_build_object(
    'id', pid,
    'slug', (select slug from public.products where id = pid),
    'removed', coalesce(to_jsonb(removed), '[]'::jsonb),
    'images', coalesce((select jsonb_agg(jsonb_build_object('id', id, 'path', path, 'sort_order', sort_order) order by sort_order)
                        from public.product_images where product_id = pid), '[]'::jsonb)
  );
end;
$$;

revoke all on function public.admin_save_product(jsonb, uuid[], jsonb, boolean) from public, anon;
grant execute on function public.admin_save_product(jsonb, uuid[], jsonb, boolean) to authenticated;

-- Dashboard numbers in one request
create or replace function public.admin_stats()
returns jsonb
language sql
security invoker
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'products',   (select count(*) from public.products),
    'categories', (select count(*) from public.categories),
    'occasions',  (select count(*) from public.occasions),
    'faqs',       (select count(*) from public.faqs),
    'no_images',  (select count(*) from public.products p
                   where not exists (select 1 from public.product_images i where i.product_id = p.id))
  );
$$;

revoke all on function public.admin_stats() from public, anon;
grant execute on function public.admin_stats() to authenticated;

-- make the API see the new functions right away
notify pgrst, 'reload schema';
